testing: 1
pathToImages: /home/jan/Dokumente/ygopro_vs_links_beta/pics
pathToApkFolder: ygopro
pathToOldApkFolder: ygoproOld
patchObb: patch.49.co.ygopro.ygoproandroid.obb
originalScriptFolder: /home/jan/Dokumente/ygopro-percy/script